from gb import MC, FILL

def num(v, *units):
    out = [str(v)]
    for u in units: out += [f"{v} {u}", f"{v}{u}"]
    return out

EXTRA = {
"0": [
 FILL("fill-period", "Fill in: period from frequency", "A wave has F = 50 Hz. Its period T is ____ seconds.",
      num("0.02", "s", "sec", "seconds") + ["1/50"], ["T = 1 / F.", "1 ÷ 50 = ?", "0.02 s, which is 20 ms."], ["T = 1/F = 1/50 = 0.02 s (20 ms)."],
      "Period and frequency are the first thing every lab asks you to read off a plot.", ref="vocab"),
 FILL("fill-freq", "Fill in: frequency from period", "One repeat of a wave takes 0.004 s. Its frequency is ____ Hz.",
      num("250", "Hz", "hz"), ["F = 1 / T.", "1 ÷ 0.004 = ?", "It's 250."], ["F = 1/T = 1/0.004 = 250 Hz."],
      "You'll convert between these constantly: pitch trackers report Hz, waveforms show you seconds.", ref="vocab"),
 MC("mc-dial-A", "Which dial?", "In 3·cos(2π·5·t + π), which number is the amplitude?",
    ["3", "5", "π", "2π"], 0,
    ["Right: the number in front sets how tall the wave is.", "5 is the frequency (repeats per second).", "π is the starting angle (phase).", "2π is just 'one lap'; it's in every sinusoid."],
    ["Amplitude = the number multiplying the cosine = 3."], "Reading the three dials correctly is the first step of every Lab 3 question.", ref="formula"),
 MC("mc-change-F", "What happens if…", "You change 2·cos(2π·100·t) to 2·cos(2π·200·t). What happens to the plot?",
    ["Twice as many repeats per second (squished sideways)", "Twice as tall", "Starts at the bottom", "Nothing changes"], 0,
    ["Right: F doubled, so the period halved (10 ms → 5 ms).", "Height is A, which stayed 2.", "Starting point is ϕ, which stayed 0.", "F changed from 100 to 200."],
    ["Only F changed, from 100 Hz to 200 Hz: twice as many cycles, each half as long."], "Predicting the plot from the formula is Lab 3 Q2.", ref="formula"),
 MC("mc-db", "Decibels", "Sound B's amplitude is twice sound A's. How much louder is B?",
    ["+6 dB", "+2 dB", "+20 dB", "twice as many dB"], 0,
    ["Right: ×2 amplitude = +6 dB.", "dB don't add the ratio directly; it's 20·log₁₀(2) ≈ 6.", "+20 dB is ×10 amplitude.", "dB is a log scale; ×2 is always +6 dB, whatever the starting level."],
    ["20·log₁₀(2) ≈ 20 × 0.301 ≈ 6 dB."], "Audio meters, spec sheets and spectrum plots are all in dB.", ref="vocab"),
 MC("mc-plot", "Which plot?", "Time goes left to right, frequency bottom to top, darkness shows strength. What is it?",
    ["A spectrogram", "A waveform", "A spectrum", "A phase plot"], 0,
    ["Right: a spectrum for every moment, side by side.", "A waveform has pressure (not frequency) on the vertical axis.", "A spectrum has frequency on the horizontal axis and no time axis.", "Phase plots show angle against frequency."],
    ["Time on x, frequency on y, darkness = amplitude: a spectrogram."], "Spectrograms are the main picture in phonetics and in every speech tool.", ref="spectrum"),
],
"3": [
 FILL("fill-ts", "Fill in: time between samples", "Fₛ = 20,000 Hz. The time between samples Tₛ is ____ seconds.",
      num("0.00005", "s") + ["5e-5", "1/20000", "0.05 ms", "0.05ms", "50 µs", "50µs", "50 us"], ["Tₛ = 1 / Fₛ.", "1 ÷ 20,000.", "0.00005 s (50 microseconds)."], ["Tₛ = 1/20,000 = 0.00005 s."],
      "Sampling rates are always given in Hz; converting to seconds between samples is the first line of Lab 2.", ref="sampling"),
 FILL("fill-count", "Fill in: how many samples", "A 1.5-second recording at Fₛ = 16,000 Hz has ____ samples.",
      num("24000") + ["24,000"], ["samples = seconds × Fₛ.", "1.5 × 16,000.", "24,000."], ["1.5 × 16,000 = 24,000 samples."],
      "Array lengths in every lab notebook come from this multiplication.", ref="sampling"),
 FILL("fill-levels", "Fill in: bits to levels", "An 8-bit recording has ____ possible levels.",
      num("256"), ["levels = 2^bits.", "2⁸.", "256."], ["2⁸ = 256 levels."], "Bit depth is on every recording device and audio export dialog.", ref="quant"),
 FILL("fill-nyq", "Fill in: Nyquist", "Fₛ = 44,100 Hz. The Nyquist frequency is ____ Hz.",
      num("22050", "Hz") + ["22,050", "22,050 Hz"], ["Nyquist = Fₛ / 2.", "44,100 ÷ 2.", "22,050."], ["44,100 ÷ 2 = 22,050 Hz."], "That's why CDs can hold everything up to about 22 kHz, just above human hearing.", ref="alias"),
 MC("mc-alias", "Where does it land?", "A 6,000 Hz tone is sampled at Fₛ = 8,000 Hz. What frequency does it show up as?",
    ["2,000 Hz", "6,000 Hz", "4,000 Hz", "14,000 Hz"], 0,
    ["Right: Nyquist is 4,000; 6,000 is above it, so it folds to 8,000 − 6,000 = 2,000.", "6,000 is above Nyquist (4,000), so it can't be stored honestly.", "4,000 is the Nyquist frequency itself, not the alias.", "You added Fₛ; the fold is Fₛ − F."],
    ["Nyquist = 4,000 Hz.", "6,000 > 4,000, so it aliases to 8,000 − 6,000 = 2,000 Hz."], "This is exactly Lab 2 Q13–Q15.", ref="alias"),
 MC("mc-better", "Better copy", "Which change gives a more accurate copy of the wave? (Lab 2 Q9)",
    ["Raise the sampling rate Fₛ", "Record for longer", "Use a lower sampling rate", "Change the wave's frequency"], 0,
    ["Right: more samples per second trace the wave more closely.", "Longer just gives more samples of the same quality.", "Fewer samples per second = worse copy (and more aliasing).", "You're measuring the wave; you don't get to change it."],
    ["Higher Fₛ (equivalently, shorter Tₛ) = more points per cycle."], "The sample-rate menu in every audio app is this choice.", ref="sampling"),
],
"4": [
 FILL("fill-mag", "Fill in: magnitude", "The magnitude of 5 + 12j is ____.",
      num("13"), ["Pythagoras: √(a² + b²).", "√(25 + 144) = √169.", "13."], ["|5 + 12j| = √(25 + 144) = 13."], "Magnitudes are the heights in every spectrum plot.", ref="numbers"),
 FILL("fill-conj", "Fill in: conjugate", "The conjugate of 2 − 7j is ____.",
      ["2 + 7j", "2+7j", "2 + 7i", "2+7i", "2 + j7", "2+j7"], ["Flip the sign of the j part only.", "The real part 2 stays.", "2 + 7j."], ["Conjugate: keep 2, flip −7j to +7j → 2 + 7j."], "Negative-frequency coefficients are always the conjugates of the positive ones.", ref="numbers"),
 MC("mc-euler", "Easy point", "What is e^{jπ} as a plain number?",
    ["−1", "1", "j", "−j"], 0,
    ["Right: angle π is half a lap, straight left.", "1 is e^{j0} (angle 0, straight right).", "j is e^{jπ/2} (straight up).", "−j is e^{−jπ/2} (straight down)."],
    ["e^{jπ} is the point at angle π (180°) on the unit circle: straight left, which is −1."], "The four easy points come up in almost every coefficient calculation.", ref="euler"),
 MC("mc-angle", "Direction", "What is the angle of the complex number −4j?",
    ["−π/2 (straight down)", "π/2 (straight up)", "π (straight left)", "0 (straight right)"], 0,
    ["Right: −4j is 4 steps straight down.", "Straight up would be +4j.", "Straight left would be −4.", "Straight right would be +4."],
    ["−4j has no real part and a negative j part: straight down, angle −π/2."], "Phase spectra are made of exactly these angles.", ref="numbers"),
 MC("mc-two-spin", "Two spinners", "e^{j2π·10·t} + e^{−j2π·10·t} equals…",
    ["2·cos(2π·10·t)", "2·sin(2π·10·t)", "0", "e^{j4π·10·t}"], 0,
    ["Right: the up-down parts cancel, the left-right parts double.", "The sine parts are the ones that cancel.", "Only the up-down parts cancel; the left-right parts add.", "Adding doesn't add the exponents; multiplying would."],
    ["The two dots spin opposite ways at 10 Hz. Up-down: +sin and −sin cancel. Left-right: cos + cos = 2·cos."], "This is why every real signal's FFT is mirror-symmetric.", ref="spinner"),
 FILL("fill-phasor", "Fill in: amplitude from X", "A two-sided spectrum shows X = 1.5 at 100 Hz. The cosine's amplitude A is ____.",
      num("3"), ["Two-sided: each side holds half the amplitude.", "A = 2·|X|.", "2 × 1.5 = 3."], ["A = 2|X| = 2 × 1.5 = 3."], "Forgetting this factor of 2 makes every spectrum look half as tall as it should.", ref="def"),
],
"5": [
 FILL("fill-harm", "Fill in: harmonic", "F₀ = 110 Hz. The 4th harmonic is at ____ Hz.",
      num("440", "Hz"), ["The k-th harmonic is at k·F₀.", "4 × 110.", "440."], ["4 × 110 = 440 Hz."], "Musical notes and vowel harmonics both follow this rule.", ref="spectrum"),
 FILL("fill-T0", "Fill in: period from F₀", "F₀ = 5 Hz. The period T₀ is ____ seconds.",
      num("0.2", "s") + ["1/5"], ["T₀ = 1/F₀.", "1 ÷ 5.", "0.2 s."], ["T₀ = 1/5 = 0.2 s."], "Lab 4 Q1.", ref="spectrum"),
 FILL("fill-A-from-ab", "Fill in: amplitude from a and b", "A harmonic has aₖ = 6 and bₖ = 8. Its amplitude Aₖ is ____.",
      num("10"), ["Aₖ = √(aₖ² + bₖ²).", "√(36 + 64) = √100.", "10."], ["√(36 + 64) = 10."], "Converting between the forms is a daily task once you use np.fft.", ref="forms"),
 MC("mc-which-harm", "Which harmonic?", "F₀ = 50 Hz. A component at 250 Hz is which harmonic?",
    ["The 5th", "The 250th", "The 4th", "Not a harmonic"], 0,
    ["Right: 250 ÷ 50 = 5.", "k is frequency ÷ F₀, not the frequency itself.", "4 × 50 = 200, not 250.", "250 is a whole multiple of 50, so it is a harmonic."],
    ["k = 250 / 50 = 5."], "Reading harmonic numbers off a spectrum is how pitch is measured.", ref="spectrum"),
 MC("mc-detector", "The detector", "x(t) = 4·cos(2π·10·t) + 2·cos(2π·30·t), F₀ = 10 Hz. What is X₂ (two-sided)?",
    ["0", "2", "1", "4"], 0,
    ["Right: nothing in x is at 2 × 10 = 20 Hz, so the detector finds nothing.", "2 would be X₁ (half of 4).", "1 would be X₃ (half of 2).", "4 is the full amplitude of the 10 Hz part, not a coefficient at 20 Hz."],
    ["Harmonic 2 is at 20 Hz. The wave has parts at 10 and 30 Hz only, so X₂ = 0."], "Lab 4 Q9 asks exactly this.", ref="coef"),
 MC("mc-orth", "Averages to zero", "Averaged over one repeat, what is cos(2π·F₀·t) × cos(2π·3F₀·t)?",
    ["0", "½", "1", "It depends on F₀"], 0,
    ["Right: different harmonics cancel out on average (orthogonality).", "½ is for a harmonic times ITSELF.", "The product of two cosines is never 1 on average.", "It's 0 for any F₀, as long as the harmonics are different."],
    ["Different harmonics: the product goes above and below zero equally, so the average is 0."], "This one fact is what makes Fourier analysis (and Wi-Fi) work.", ref="coef"),
],
"6": [
 FILL("fill-bin", "Fill in: bin spacing", "Fₛ = 8,000 Hz, N = 256. The bin spacing is ____ Hz.",
      num("31.25", "Hz"), ["Bin spacing = Fₛ / N.", "8,000 ÷ 256.", "31.25."], ["8,000 / 256 = 31.25 Hz."], "Every spectrum in the labs has this resolution limit.", ref="dft"),
 FILL("fill-which-bin", "Fill in: which bin", "Fₛ = 16,000 Hz, N = 1,024 (spacing 15.625 Hz). The 500 Hz component is in bin ____.",
      num("32"), ["bin = frequency ÷ spacing.", "500 ÷ 15.625.", "32."], ["500 / 15.625 = 32."], "Finding bins is how you read numbers off np.fft output.", ref="dft"),
 FILL("fill-nperseg", "Fill in: samples per frame", "Fₛ = 16,000 Hz and a 20 ms frame. nperseg = ____ samples.",
      num("320"), ["ms → seconds, then × Fₛ.", "0.020 × 16,000.", "320."], ["0.020 × 16,000 = 320."], "Lab 7/8 parameter.", ref="stft"),
 FILL("fill-noverlap", "Fill in: overlap", "nperseg = 400 and hop = 160. noverlap = ____ samples.",
      num("240"), ["noverlap = nperseg − hop.", "400 − 160.", "240."], ["400 − 160 = 240."], "scipy.signal.stft asks for exactly this number.", ref="stft"),
 MC("mc-leak", "Leak or not?", "A 25 ms rectangular window (grid spacing 40 Hz). Which tone does NOT leak?",
    ["400 Hz", "410 Hz", "430 Hz", "450 Hz"], 0,
    ["Right: 400 ÷ 40 = 10, a whole number, so it sits exactly on a bin.", "410 ÷ 40 = 10.25: between bins, leaks.", "430 ÷ 40 = 10.75: leaks.", "450 ÷ 40 = 11.25: leaks."],
    ["Only tones that are whole multiples of the 40 Hz grid avoid leakage: 400 = 10 × 40."], "Lab 6/7's windowing questions.", ref="window"),
 MC("mc-band", "Narrow or broad?", "You want to see the harmonics as thin horizontal lines. Which window?",
    ["A long window (narrow-band)", "A short window (broad-band)", "No window", "A window of exactly one sample"], 0,
    ["Right: long window = fine frequency detail.", "Short windows blur frequency; you'd see vertical stripes instead.", "You always need some window to make a spectrogram.", "One sample has no frequency information at all."],
    ["Fine frequency resolution needs a long window: narrow-band spectrogram."], "The one conceptual question Day 8 always asks.", ref="stft"),
],
"9": [
 FILL("fill-f0", "Fill in: F0 from a lag", "Fₛ = 16,000 Hz; the first autocorrelation peak is at lag 100. F0 = ____ Hz.",
      num("160", "Hz"), ["F0 = Fₛ ÷ lag.", "16,000 ÷ 100.", "160."], ["16,000 / 100 = 160 Hz."], "Lab 8's pitch tracker does exactly this for every frame.", ref="f0"),
 FILL("fill-dot", "Fill in: dot product", "x = [1, 2, 3], y = [4, 0, −1]. x · y = ____.",
      num("1"), ["Multiply position by position, then add.", "1·4 + 2·0 + 3·(−1).", "4 + 0 − 3 = 1."], ["4 + 0 − 3 = 1."], "Autocorrelation is many dot products in a row.", ref="dot"),
 FILL("fill-wer", "Fill in: WER", "Reference has 20 words. The system made 2 substitutions, 1 deletion and 1 insertion. WER = ____ %.",
      num("20", "%"), ["WER = (S + D + I) ÷ N.", "(2 + 1 + 1) ÷ 20.", "0.20 = 20%."], ["4 / 20 = 20%."], "Every ASR benchmark reports WER.", ref="wer"),
 MC("mc-lag0", "Which peak?", "Autocorrelation values: lag 0: 50, lag 40: 31, lag 80: 22. What is the period?",
    ["40 samples", "0 samples", "80 samples", "50 samples"], 0,
    ["Right: the first peak AFTER lag 0.", "Lag 0 is always the biggest; it's the signal matched with itself.", "80 is the second repeat (2 × 40).", "50 is a score, not a lag."],
    ["Skip lag 0; the first peak after it is at lag 40."], "Picking the wrong peak is the most common pitch-tracking bug.", ref="auto"),
 MC("mc-heur", "Throw it out?", "A frame gives F0 = 2,500 Hz. With a 75–600 Hz range, what do you do?",
    ["Reject it: no voice is that high", "Keep it", "Halve it to 1,250 Hz", "Use it as the formant"], 0,
    ["Right: it's probably a noisy or voiceless frame.", "2,500 Hz is far above any human pitch.", "Halving doesn't fix a frame that has no real period.", "Formants aren't measured this way."],
    ["2,500 Hz is outside 75–600 Hz, so the frame is skipped."], "Real pitch trackers (Praat included) all use a range like this.", ref="heur"),
],
"11": [
 FILL("fill-pre", "Fill in: pre-emphasis", "x = [1, 3], α = 0.9. y[1] = x[1] − α·x[0] = ____.",
      num("2.1"), ["Plug in: 3 − 0.9 × 1.", "0.9 × 1 = 0.9.", "3 − 0.9 = 2.1."], ["y[1] = 3 − 0.9 = 2.1."], "Pre-emphasis is the first line of every MFCC function.", ref="pre"),
 FILL("fill-energy", "Fill in: energy", "Frame x = [1, −2, 2]. Energy Σx² = ____.",
      num("9"), ["Square each sample.", "1 + 4 + 4.", "9."], ["1 + 4 + 4 = 9."], "Energy is often the 13th feature.", ref="energy"),
 FILL("fill-quef", "Fill in: quefrency → F0", "Fₛ = 48,000 Hz, cepstral peak at quefrency 240. F0 = ____ Hz.",
      num("200", "Hz"), ["frequency = Fₛ ÷ quefrency.", "48,000 ÷ 240.", "200."], ["48,000 / 240 = 200 Hz."], "Cepstral pitch tracking.", ref="cep"),
 FILL("fill-delta", "Fill in: delta", "A feature over frames: [2, 5, 9]. Δ[1] = (x[2] − x[0]) / 2 = ____.",
      num("3.5"), ["Use the neighbours on both sides.", "(9 − 2) / 2.", "3.5."], ["(9 − 2)/2 = 3.5."], "Deltas are 13 of the 39 classic features.", ref="delta"),
 MC("mc-39", "The 39 numbers", "The classic 39 ASR features per frame are…",
    ["13 MFCCs + 13 deltas + 13 delta-deltas", "39 filterbank energies", "39 FFT bins", "13 MFCCs from 3 frames"], 0,
    ["Right.", "Filterbank energies come before the DCT; there are usually ~26.", "Raw FFT bins are hundreds of numbers.", "The extra 26 are changes (velocity, acceleration), not copies."],
    ["13 + 13 + 13 = 39."], "You'll see '39-dimensional MFCC' in older ASR papers.", ref="mfcc"),
 MC("mc-quef-dir", "Higher voice", "Speaker A's cepstral peak is at a lower quefrency than speaker B's. Who has the higher pitch?",
    ["Speaker A", "Speaker B", "Same pitch", "Can't tell"], 0,
    ["Right: frequency = Fₛ ÷ quefrency, so smaller quefrency = higher F0.", "Quefrency runs backwards: bigger quefrency = lower pitch.", "Different peaks mean different pitches.", "You can: just divide Fₛ by each quefrency."],
    ["Lower quefrency → higher F0."], "Koo's favourite trick question.", ref="cep"),
],
}
